#!/bin/bash
#create directory for output
mkdir ~/research 2> /dev/null

echo "A Script"
date
echo -e "Uname info: $(uname -a) \n"
echo -e "IP Info: $(ip addr | head -9 | tail -1) \n"
echo -e "Hostname: $(hostname) \n"
sudo find /home/ -type f -perm 777 >> ~/research/sys_info.txt
ps aux --sort -%mem | awk {'print $1,$2 $3 $4 $11'} | head >> ~/research/sys_info.txt
